apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gpulink
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: gpulink
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: gpulink
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
