apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres-storageclass.yaml
  - postgres-pv.yaml
  - postgres-pgbackrest-configmap.yaml
  - postgres-pgbackrest-service.yaml

patches:
  - path: postgres-pgbackrest-patch.yaml
