apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gpulink-postgres
  labels:
    app.kubernetes.io/part-of: gpulink
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
