apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pgbackrest-config
  namespace: gpulink
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: gpulink
    app.kubernetes.io/component: backup
data:
  pgbackrest.conf: |
    [gpulink]
    pg1-path=/var/lib/postgresql/data/pgdata
    pg1-socket-path=/var/run/postgresql

    [global]
    tls-server-address=*
    tls-server-port=8432
    tls-server-auth=gpulink-repository=gpulink
    tls-server-ca-file=/etc/pgbackrest/tls/ca.crt
    tls-server-cert-file=/etc/pgbackrest/tls/server.crt
    tls-server-key-file=/etc/pgbackrest/tls/server.key

    log-level-console=info
    log-level-file=off
