CREATE TABLE workers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  version TEXT NOT NULL,
  base_url TEXT,
  status TEXT NOT NULL
    CHECK (status IN ('online', 'offline')),
  drain_mode BOOLEAN NOT NULL DEFAULT FALSE,
  labels_json JSONB NOT NULL,
  capabilities_json JSONB NOT NULL,
  adapter_manifests_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  adapter_health_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  warm_models_json JSONB NOT NULL,
  model_inventory_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  gpu_inventory_json JSONB NOT NULL,
  last_seen_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE jobs (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  type TEXT NOT NULL,
  priority INTEGER NOT NULL,
  status TEXT NOT NULL
    CHECK (
      status IN (
        'queued',
        'leased',
        'running',
        'succeeded',
        'failed',
        'cancelled'
      )
    ),
  gpu_count INTEGER NOT NULL
    CHECK (gpu_count = 1),
  min_vram_mib INTEGER NOT NULL,
  required_capabilities_json JSONB NOT NULL,
  requested_model TEXT,
  payload_json JSONB NOT NULL,
  result_json JSONB,
  error_json JSONB,
  assigned_worker_id TEXT REFERENCES workers(id),
  assigned_gpu_uuid TEXT,
  lease_id TEXT,
  lease_expires_at BIGINT,
  attempt INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL,
  idempotency_key TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (project_id, idempotency_key)
);

CREATE INDEX jobs_queue_index
  ON jobs (
    status,
    priority DESC,
    created_at ASC
  );

CREATE INDEX jobs_worker_index
  ON jobs (
    assigned_worker_id,
    status
  );

CREATE TABLE events (
  sequence BIGINT
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
  type TEXT NOT NULL,
  subject_id TEXT,
  payload_json JSONB NOT NULL,
  created_at BIGINT NOT NULL
);
